fieldLayouts:
  60c1a8d0-b403-479b-aafe-c26ede8bd731:
    tabs:
      -
        elements:
          -
            fieldUid: d271d26b-1969-4fc5-9577-b1f7a678b65c # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 151efc59-5eab-4756-a081-1de8174a02ba # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Header Informations'
        sortOrder: 1
handle: headerInformations
name: 'Header Informations'
sortOrder: 1
