fieldLayouts:
  096198b2-c2da-496a-bcbd-68bc244f017b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blogContent
hasUrls: true
name: Blog-Content
settings:
  path: ./uploads/blog-content
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: none
type: craft\volumes\Local
url: '@web/uploads/blog-content'
