fieldLayouts:
  cf9f69e3-6668-4f7e-b009-43c544e09fb2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: f64aeb78-cc50-4afe-bd75-23d50746c9ed # PreviewImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d39e1790-9b14-4a08-b249-615eae6a62a1 # Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: e1f79275-cdd9-440f-9b91-0d851bc664d6 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8314c389-170f-42d9-9f0e-9672fafff415 # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0aeff042-20ed-44db-91ca-0632fbdc43be # Preview Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 73568354-2f80-4596-b606-e4de3a380525 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
hasTitleField: false
name: Default
section: 6103c328-74b9-4433-a617-4005e60428e5 # Blog Posts
sortOrder: 1
titleFormat: '{blogPostHeading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
