fieldLayouts:
  4dec0ed1-311d-45bd-8042-ecc07786307d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b56fb6f8-f8a8-47d9-9bce-c0722b082ff1 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3c6de1a3-4ec5-40ef-be11-18556ebd9104 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 802e5e16-a2ed-481f-952b-9b0f596dd6bb # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: babc2a04-f8e5-4fca-b4f1-b138b8b3ae1b # Button URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: successNewsletterSubscription
hasTitleField: true
name: 'Success Newsletter Subscription'
section: 654840ae-2367-498e-99f2-1d6578873cb9 # Success Newsletter Subscription
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
