field: 4e9e9279-b855-450f-b36c-0fcf86622f73 # Location
fieldLayouts:
  b4cfa4aa-ae2e-4ee9-ac1d-44f3dc3beb63:
    tabs:
      -
        elements:
          -
            fieldUid: 7e849a90-ebc0-42ab-8fec-3a5f85a51f9b # country
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae499f75-dfb8-4b59-852e-e7c98a6019fe # flag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c859d084-513e-4f5d-a9f2-318006e2c114 # capacity
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 58950036-eef8-4aef-a6a2-5ed8f492f9f8 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1606f661-fa3f-467b-9c76-5d1fdf5fee6d # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7e849a90-ebc0-42ab-8fec-3a5f85a51f9b: # country
    columnSuffix: ffjhyxfc
    contentColumnType: text
    fieldGroup: null
    handle: country
    instructions: ''
    name: country
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  1606f661-fa3f-467b-9c76-5d1fdf5fee6d: # Button Link
    columnSuffix: muikboxu
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  58950036-eef8-4aef-a6a2-5ed8f492f9f8: # Button Text
    columnSuffix: akyrfksw
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  ae499f75-dfb8-4b59-852e-e7c98a6019fe: # flag
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: flag
    instructions: ''
    name: flag
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:48ecb720-dbbf-40c8-ade7-b84c53975070' # Advantages Icons
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:48ecb720-dbbf-40c8-ade7-b84c53975070' # Advantages Icons
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c859d084-513e-4f5d-a9f2-318006e2c114: # capacity
    columnSuffix: ckxsuxpx
    contentColumnType: text
    fieldGroup: null
    handle: capacity
    instructions: ''
    name: capacity
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: location
name: location
sortOrder: 1
