columnSuffix: bciuewff
contentColumnType: text
fieldGroup: b91a7615-d118-482e-820e-f383a266ac1e # Asset Management
handle: assetManagementSubheading
instructions: ''
name: Subheading
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
