columnSuffix: ptztswfd
contentColumnType: datetime
fieldGroup: 2f4e054b-a655-44f4-8f45-656936edd3f9 # Blog Posts
handle: blogPostDate
instructions: ''
name: Date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
