columnSuffix: null
contentColumnType: string
fieldGroup: 3314e328-6e73-4f75-be24-9bf00bd38061 # Mining
handle: miningEarnings
instructions: ''
name: Earnings
searchable: false
settings:
  columns:
    __assoc__:
      -
        - bf8ad432-6ac7-495a-954f-21fbd5586ddc # Heading
        -
          __assoc__:
            -
              - width
              - ''
      -
        - b5740af6-56af-4394-8958-11310ed9823b # Subheading
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 977d7b44-78d2-420f-a37c-997ef0966924
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_miningearnings}}'
  fieldLayout: matrix
  maxRows: '1'
  minRows: '1'
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
