columnSuffix: fxreeacr
contentColumnType: text
fieldGroup: 3314e328-6e73-4f75-be24-9bf00bd38061 # Mining
handle: miningText
instructions: ''
name: Text
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
