columnSuffix: null
contentColumnType: string
fieldGroup: 3314e328-6e73-4f75-be24-9bf00bd38061 # Mining
handle: miningFarms
instructions: ''
name: Farms
searchable: false
settings:
  contentTable: '{{%matrixcontent_miningfarms}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
