columnSuffix: null
contentColumnType: string
fieldGroup: acc82756-cf0e-4738-9ff4-0bfe0104787c # Publications
handle: publicationsLogos
instructions: ''
name: Logos
searchable: false
settings:
  contentTable: '{{%stc_publicationslogos}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
