columnSuffix: oncmuwwn
contentColumnType: string(255)
fieldGroup: b4a4dd8c-1033-45c0-8c69-c6985f5e45f2 # Statement
handle: statementCardButtonUrl
instructions: ''
name: 'Card Button URL'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
