columnSuffix: jyiefbyt
contentColumnType: string(255)
fieldGroup: 503735ce-b504-4ae6-8af6-1717fe0e2a5a # Success Form
handle: successFormButtonUrl
instructions: ''
name: 'Button URL'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
