columnSuffix: amxepctb
contentColumnType: text
fieldGroup: a33e4f14-33b1-484b-ab4d-767e93c59209 # Success Newlsetter Subscription
handle: successNewsletterSubscriptionButtonText
instructions: ''
name: 'Button Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
