columnSuffix: null
contentColumnType: string
fieldGroup: fde6d049-18ea-4505-ad38-0a99678e8b56 # Team Cards
handle: teamCardImage
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:e3a19840-54cf-4fe5-912a-bed2f923f455' # Team
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:48ecb720-dbbf-40c8-ade7-b84c53975070' # Icons
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e3a19840-54cf-4fe5-912a-bed2f923f455' # Team
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
