defaultPlacement: end
enableVersioning: true
handle: formSubmissions
name: 'Form Submissions'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3e857d4d-6f04-4ebe-8515-2954fe9e4102: # Decom Web
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  659e43ae-5d94-496b-96d2-0092b7fb5ea7: # Decom Web (EN)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
